## Board size
BoardWidth: 6
BoardHeight: 3
square_size: 40 # Distance between two neighboring crosspoints (unit:mm)

## Bag config
BagName: "/data/catkin_calib/src/EF-Calib/record_bag/trial_A_3.bag"
StorePath: "/data/catkin_calib/src/EF-Calib/record_bag/"
cornerBagPath: "/data/catkin_calib/src/EF-Calib/record_bag/corner_info.bag"   
circleBagPath: "/data/catkin_calib/src/EF-Calib/record_bag/circle_info.bag"

## Estimator config
log_path: "/data/catkin_calib/logs"
init_window_size: 8

conv_cam_width: 1280
conv_cam_height: 1024
ev_cam_width: 346
ev_cam_height: 260

board_width: 6
board_height: 3

knot_distance: 0.035
continue_number: 15

opt_time: 40